### ISSUE TITLE
I just wanted to thank you

### ISSUE THREAD

**Issue by Unknown6656** [stephan3321/LDD-Newly-Added-Parts#5]
I just wanted to say "thanks" for keeping this project alive even though LDD has been discontinued.

I'm currently re-visiting an old project of mine, a large Version of the Star Wars Venator-class Star Destroyer _(and I mean a really large version -- it is only half finished and contains over 24'900 bricks and is over 1.5m (5ft) long.)

![image](https://user-images.githubusercontent.com/8807985/211920530-a4e2f9bf-6225-4f83-9025-5768dcf079c0.png)

I hope that with your files, I will be able to improve this build over the upcoming months and years.

Thanks again for everything!

**Comment by stephan3321** [comment]
You are welcome!
